import Footer from '@/components/ui/Footer/Footer';
import Header from '@/components/ui/Header/Header';
import Wrapper from '@/components/ui/Wrapper/Wrapper';
import CartProvider from '@/providers/CartProvider';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import '../styles/globals.css';
import '../styles/nullstyle.css';

export const metadata: Metadata = {
	title: 'Avion',
	description: 'Generated by create next app',
	icons: './logo.svg',
};

export default function RootLayout({
	children,
	cart
}: Readonly<{
	children: ReactNode,
	cart: ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<CartProvider>
					<Wrapper>
						{cart}
						<Header />
						<div id='content'>{children}</div>
						<Footer />
					</Wrapper>
				</CartProvider>
			</body>
		</html>
	);
}
