import Footer from '@/components/ui/Footer/Footer';
import Header from '@/components/ui/Header/Header';
import Wrapper from '@/components/ui/Wrapper/Wrapper';
import type { Metadata } from 'next';
import '../styles/globals.css';
import '../styles/nullstyle.css';

export const metadata: Metadata = {
	title: 'Avion',
	description: 'Generated by create next app',
	icons: './logo.svg',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Wrapper>
					<Header />
					<div id='content'>{children}</div>
					<Footer />
				</Wrapper>
			</body>
		</html>
	);
}
